// <auto-generated />
using Mechanic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mechanic.EFcore;
#nullable disable

namespace Mechanic.Api.Migrations
{
    [DbContext(typeof(MechanicDbContext))]
    [Migration("20250506192406_AddClientJobRelation")]
    partial class AddClientJobRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("Client", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Mechanic.Job", b =>
                {
                    b.Property<string>("jobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("customerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("licensePlate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("manufacturingYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("severity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("workCategory")
                        .HasColumnType("INTEGER");

                    b.HasKey("jobId");

                    b.HasIndex("customerId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Mechanic.Job", b =>
                {
                    b.HasOne("Client", "Client")
                        .WithMany()
                        .HasForeignKey("customerId");

                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
